### ISSUE TITLE
Welcome Display

### ISSUE THREAD

**Issue by nelsonic** [dwyl/smart-home-security-system#10]
At the entrance to the building we will have a small screen that is _unmissable_ we will refer to as the **Welcome Display**.
The display will show a basic "Welcome Home {FirstName}" to the person when they successfully authenticate at the door
or show "Hello Stranger!" when the device they are using is unrecognised.
Later we will use this display to show the most relevant information to the person entering the building.
But for now, it's just "Welcome". 

# Todo

+ [x] Connect the Welcome Display to the Raspberry Pi 4 running the Auth Server [smart-home-auth-server](https://github.com/dwyl/smart-home-auth-server)
+ [x] If a _recognised_ device (NFC/RFID tag) is scanned on the reader (connected to the RPiZero), greet the person.
+ [ ] If an _unrecognised_ display "Hello Stranger!" and Basic instructions to register the device. 
+ [ ] Send a notification to connected devices informing people @home that there is an unrecognised device i.e. new person at the door who needs help getting in the building.
+ [ ] Allow the person to register their device by authenticating using `auth-plug` and associating the device
  > **Note**: approval of the person/device will still be required by the "admin", but this can be done remotely (_especially if the Pi Camera has high enough quality_). This is basically a "door entry system" akin to the [video door entry systems](https://en.wikipedia.org/wiki/Door_phone) that have been common place in buildings since the 1980's. Most modern apartment buildings have a camera on the intercom that allows the person answering the door from their apartment to _see_ who is requesting access. 

## Stretch Goals: 
+ [ ] **`before`** the person scans their device, **Show instructions** to people to **scan** their **device** on the **NFC reader** 
  e.g. "_Hello! Please scan your device to enter the building._" 👋 
+ [ ] **Saver Energy** by only powering the display when a person is nearby (turn it off after 2 minutes to save power). 🔋 
  e.g. using a relay to power the display and the Pi Cam to detect movement. 
+ [ ] **Use Pi Camera** https://github.com/dwyl/learn-nerves/issues/5 to **detect motion** and turn on display. 📷

**Comment by nelsonic** [comment]
@th0mas as discussed on the standup call this morning, the **Welcome Display** will be a reasonably large **40" 1080p screen** (_Old but still perfectly working order LCD TV_) that consumes around [50W](https://understandsolar.com/how-many-watts-does-a-tv-use/) of power. We obviously don't want to keep this screen on 24/7 as it will use more power than all the Raspberry Pis @home _combined_; hence powering the screen via relay. 🔋 
The Amazon order containing your POE splitter has a relay:
![image](https://user-images.githubusercontent.com/194400/87132946-83c39900-c28e-11ea-9282-79c6bf3fe411.png)
https://smile.amazon.co.uk/gp/product/B078Q326KT
![image](https://user-images.githubusercontent.com/194400/87133229-ed43a780-c28e-11ea-8bce-29d61141cf18.png)
It should arrive tomorrow (_or by Monday at the latest_). 

Please let us know if you need any electrical wire in order to connect the relay to a 230V appliance in order to test this feature.
I'd advise you to use a simple **light**💡  to simulate the "screen" being switched on/off by the relay.  But if you're feeling confident in the relay and want to hack a mains power cable and connect an _actual_ monitor to the relay, LMK which cable you need.

**Comment by t0mhaines** [comment]
Currently have no wire (or tools) to hook up 230V to another device. I'm not quite sure what I'll need to get that working but i'll look into it.

Running this on a separate Raspberry Pi might be worth it to prevent any issues with the Relay/Pi taking down the entire system, it also makes for a more clear separation of concerns between *hub* and *device*.

**Comment by t0mhaines** [comment]
For rendering a GUI on our welcome display we realistically have two options:

+ Elixir Scenic - https://github.com/boydm/scenic. This is a well-supported library on Nerves and would be absolutely fine for our use case

+ JS/WebView - Theres already a well supported [Kiosk mode](https://github.com/nerves-project/nerves_system_rpi4) Nerves image that would allow us to just write normal JS for our GUI

**Comment by nelsonic** [comment]
@th0mas cool. let us know what you decide and if you need a separate PI for this part of the application. 
From the perspective of the safety of the PI the relay should shield the circuit because it's based on a 

Given the potential complexity of doing motion detection noted in https://github.com/dwyl/learn-nerves/issues/5#issuecomment-656587838 
_Maybe_ we can just use a [PIR sensor](https://www.seeedstudio.com/blog/2019/08/03/pir-sensor-introduction-and-how-pir-motion-sensor-works-with-arduino-and-raspberry-pi) to detect motion instead of going down the Camera route?
The **HC-SR501** is relatively low power and does not raise any privacy concerns. 💭 
https://www.amazon.co.uk/AZDelivery-HC-SR501-Detection-Raspberry-including/dp/B07V9GFHFW

**Comment by t0mhaines** [comment]
Looks good. That board appears to use a UART serial port though, which we're already using for the NFC reader.
I don't know if its worth finding a I2C or SPI board - although I doubt many exist, or finding a small USB-to-UART adapter

**Comment by nelsonic** [comment]
@th0mas good point on the _potential_ mutually exclusive UART devices. 👍 
_However_, its worth remembering that the **Welcome Display** will be connected to a _separate_ Raspberry PI.
So the UART will still be available on the Display RPi which can be connected to a **`PIR`** and **`Relay`**. 

The two _distinct_ RPis will be separated by **2m** and independently powered by POE.
Let's operate under the assumption that we have ***3*** Pis that each perform **_one_ job**:

1. The **_first_ RPi0** reads the NFC/RFID chips/tags and send s
2. The **RPi4** ("Nerves Hub") handles authentication requests centrally 
  and will be placed in the server rack next to the POE switch. 
(_the location is not important just know they are physically separate but connected to the same network switch_)
3. The **_second_ RPi0** powers the **Welcome Display** and is otherwise "dumb" to the rest of the system; it just displays what the Hub instructs. A _stretch_ goal for the **RPi0** powering the welcome display is to use a PIR and Relay to switch on/off the display in response to motion at the front door. 

Maybe this annotated photo of the entrance will help:

![ihome-front-door-entrance-annotated](https://user-images.githubusercontent.com/194400/87294199-49126880-c4fb-11ea-87bd-6438c75cfef5.png)

So we can still connect the PIR sensor to the RPI that feeds/powers the Welcome Display. 👍

**Comment by t0mhaines** [comment]
Whoops! that makes sense, looks like there is no problem using that motion detector then :)

**Comment by nelsonic** [comment]
@th0mas LMK if you need an extra RPi0 to connect to a Welcome Display so your setup is mirrored to "Production". 💭

**Comment by t0mhaines** [comment]
*sigh*

https://github.com/boydm/scenic_driver_nerves_rpi/issues/13

Can't currently run Scenic on an RPi4, and I doubt the RPi0 will be able to run it (it hangs on my MacBook).

I'll hack together a Js-based display for now

**Comment by t0mhaines** [comment]
Seems like RPi4 support for https://github.com/nerves-web-kiosk is lacking as well.

Might have to abandon Nerves for this display, and run Chromium on top of Raspbian as described here: https://pimylifeup.com/raspberry-pi-kiosk/

We could point it at a LiveView page on the hub? 

@nelsonic thoughts?

**Comment by nelsonic** [comment]
@th0mas that's a bummer. 😕  (_but not a brick wall_)
If anything, it might be a blessing in disguise. 💭 
If we run the displays in Kiosk mode e.g: leveraging [https://github.com/guysoft/**FullPageOS**](https://github.com/guysoft/FullPageOS) 
(_though I'm not so happy about the need for running it as [**`root`**](https://github.com/guysoft/FullPageOS#developing) ..._)
It means they are truly "dumb" and don't know anything about the rest of the system.
The default page for the Kiosk can still connect to the hub and display any content it needs to in near-real-time
using incredibly basic JS code as noted in https://github.com/dwyl/smart-home-security-system/issues/9#issuecomment-657560631 (_though I'm sure we will want a bit more than that_)

Definitely up for using `LiveView` for this, seems like a good use-case. 
Does that mean `Scenic` is out? 💭

**Comment by nelsonic** [comment]
Obviously I would _much_ prefer to run this as `Nerves` project to avoid having a _full_ OS on any of the PIs ... 💭 
Raspberry Pi 3 appears to be supported by: https://github.com/nerves-web-kiosk/kiosk_system_rpi3 💡 
@mobileoverlord the Don of `Nerves` appears to be using **`RPi3`** for his projects, so you _know_ it will work. 😉 

Happy to send you a `RPi3` so you can maintain your momentum on this and use `Scenic` ✅ 
It makes sense to use the `RPi4` as the "Hub" as it has the most power, it will eventually be controlling **`40+`** Pis once we have all the _garden/plant_ stuff up-and-running running. 

On our standup call you mentioned using a Raspberry Pi 3 A+:
https://smile.amazon.co.uk/RASPBERRY-Plate-Model-Cortex-11811853/dp/B07KKBCXLY
<img width="1327" alt="raspberry-pi-3a+" src="https://user-images.githubusercontent.com/194400/87696033-306ab280-c788-11ea-9f38-a50aa2f83508.png">

But [Raspberry Pi 3 Kiosk](https://github.com/nerves-web-kiosk/kiosk_system_rpi3#raspberry-pi-3-kiosk) appears to focus on the "B" model:

![image](https://user-images.githubusercontent.com/194400/87696768-31501400-c789-11ea-90cb-39c1aee5b3bb.png)


Please _confirm_ that it will work with the **`RPi3 A+`**. The difference in price to the **`B+`** is _negligible_. 
Guessing you'll need another **`Micro SD card`** for it too. 
Do you need anything **`else`**?
